### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by BHCHeart** [maituoy/BayesianOpt4dftu#5]
[gzr@localhost example]$ python ./example.py
Traceback (most recent call last):
  File "./example.py", line 68, in <module>
    main()
  File "./example.py", line 56, in main
    calculate(command=VASP_RUN_COMMAND, outfilename=OUTFILENAME, method='dftu', import_kpath = import_kpath)
  File "/home/gzr/intel/intelpython3/lib/python3.6/site-packages/BayesOpt4dftu/core.py", line 447, in calculate
    method, 'scf', 'pbe', import_kpath)
  File "/home/gzr/intel/intelpython3/lib/python3.6/site-packages/BayesOpt4dftu/core.py", line 140, in generate_input
    kpts=self.struct_info['kgrid_'+xc], gamma=True, **flags)
  File "/home/gzr/intel/intelpython3/lib/python3.6/site-packages/ase/utils/__init__.py", line 63, in deprecated_function
    return func(*args, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by maituoy** [comment]
Hi, the issue is caused by the incompatibility with the latest version of the ASE package. I've fixed that in the version 0.0.6. Please try to upgrade the BayesOpt4dftu and let me know if it works out for you.

**Comment by BHCHeart** [comment]
Thank you very much for your contribution and help. Now I have a doubt, that is, I still don't know the meaning of each data in the u.txt file.

**Comment by maituoy** [comment]
Depending on the 1d or 2d system you optimize, the first one or two columns are the U values sampled at each step. The last two columns are the delta bandgap and delta band.

**Comment by BHCHeart** [comment]
> Depending on the 1d or 2d system you optimize, the first one or two columns are the U values sampled at each step. The last two columns are the delta bandgap and delta band.

I am very interested in your methods and procedures, but the lack of detailed tutorials caused me a lot of confusion. I wonder if you can provide a detailed tutorial.

**Comment by maituoy** [comment]
Thanks for your suggestion. I will build a detailed tutorial on both examples.
